export const GET_STORES_INFO_REQUEST = 'GET_STORES_INFO_REQUEST';
export const GET_STORES_INFO_SUCCESS = 'GET_STORES_INFO_SUCCESS';
export const GET_STORES_INFO_FAIL = 'GET_STORES_INFO_FAIL';
export const GET_STORES_INFO_RESET = 'GET_STORES_INFO_RESET';

export const UPDATE_STORE_NAME_REQUEST = 'UPDATE_STORE_NAME_REQUEST';
export const UPDATE_STORE_NAME_SUCCESS = 'UPDATE_STORE_NAME_SUCCESS';
export const UPDATE_STORE_NAME_FAIL = 'UPDATE_STORE_NAME_FAIL';
export const UPDATE_STORE_NAME_RESET = 'UPDATE_STORE_NAME_RESET';

export const DELETE_STORE_REQUEST = 'DELETE_STORE_REQUEST';
export const DELETE_STORE_SUCCESS = 'DELETE_STORE_SUCCESS';
export const DELETE_STORE_FAIL = 'DELETE_STORE_FAIL';

export const GET_LIST_USER_RESULTS_REQUEST = 'GET_LIST_USER_RESULTS_REQUEST';
export const GET_LIST_USER_RESULTS_SUCCESS = 'GET_LIST_USER_RESULTS_SUCCESS';
export const GET_LIST_USER_RESULTS_FAIL = 'GET_LIST_USER_RESULTS_FAIL';
export const GET_LIST_USER_RESULTS_RESET = 'GET_LIST_USER_RESULTS_RESET';

export const CREATE_STORE_REQUEST = 'CREATE_STORE_REQUEST';
export const CREATE_STORE_SUCCESS = 'CREATE_STORE_SUCCESS';
export const CREATE_STORE_FAIL = 'CREATE_STORE_FAIL';

export const UPDATE_POSITION_NAME_REQUEST = 'UPDATE_POSITION_NAME_REQUEST';
export const UPDATE_POSITION_NAME_SUCCESS = 'UPDATE_POSITION_NAME_SUCCESS';
export const UPDATE_POSITION_NAME_FAIL = 'UPDATE_POSITION_NAME_FAIL';
export const UPDATE_POSITION_NAME_RESET = 'UPDATE_POSITION_NAME_RESET';

export const DELETE_POSITION_REQUEST = 'DELETE_POSITION_REQUEST';
export const DELETE_POSITION_SUCCESS = 'DELETE_POSITION_SUCCESS';
export const DELETE_POSITION_FAIL = 'DELETE_POSITION_FAIL';
export const DELETE_POSITION_RESET = 'DELETE_POSITION_RESET';

export const CREATE_POSITION_REQUEST = 'CREATE_POSITION_REQUEST';
export const CREATE_POSITION_SUCCESS = 'CREATE_POSITION_SUCCESS';
export const CREATE_POSITION_FAIL = 'CREATE_POSITION_FAIL';

export const GET_POSITION_REQUEST = 'GET_POSITION_REQUEST';
export const GET_POSITION_SUCCESS = 'GET_POSITION_SUCCESS';
export const GET_POSITION_FAIL = 'GET_POSITION_FAIL';

export const GET_TEST_REQUEST = 'GET_TEST_REQUEST';
export const GET_TEST_SUCCESS = 'GET_TEST_SUCCESS';
export const GET_TEST_FAIL = 'GET_TEST_FAIL';


export const UPDATE_TEST_REQUEST = 'UPDATE_TEST_REQUEST';
export const UPDATE_TEST_SUCCESS = 'UPDATE_TEST_SUCCESS';
export const UPDATE_TEST_FAIL = 'UPDATE_TEST_FAIL';
export const UPDATE_TEST_RESET = 'UPDATE_TEST_RESET';

export const DELETE_TEST_REQUEST = 'DELETE_TEST_REQUEST';
export const DELETE_TEST_SUCCESS = 'DELETE_TEST_SUCCESS';
export const DELETE_TEST_FAIL = 'DELETE_TEST_FAIL';
export const DELETE_TEST_RESET = 'DELETE_TEST_RESET';

export const CREATE_TEST_REQUEST = 'CREATE_TEST_REQUEST';
export const CREATE_TEST_SUCCESS = 'CREATE_TEST_SUCCESS';
export const CREATE_TEST_FAIL = 'CREATE_TEST_FAIL';
export const CREATE_TEST_RESET = 'CREATE_TEST_RESET';


export const GET_QUESTIONS_REQUEST = 'GET_QUESTIONS_REQUEST';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAIL = 'GET_QUESTIONS_FAIL';
export const GET_QUESTIONS_RESET = 'GET_QUESTIONS_RESET';


export const UPDATE_QUESTION_REQUEST = 'UPDATE_QUESTION_REQUEST';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const UPDATE_QUESTION_FAIL = 'UPDATE_QUESTION_FAIL';
export const UPDATE_QUESTION_RESET = 'UPDATE_QUESTION_RESET';

export const DELETE_QUESTION_REQUEST = 'DELETE_QUESTION_REQUEST';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_FAIL = 'DELETE_QUESTION_FAIL';
export const DELETE_QUESTION_RESET = 'DELETE_QUESTION_RESET';

export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAIL = 'CREATE_QUESTION_FAIL';
export const CREATE_QUESTION_RESET = 'CREATE_QUESTION_RESET';

export const DELETE_VARIANT_REQUEST = 'DELETE_VARIANT_REQUEST';
export const DELETE_VARIANT_SUCCESS = 'DELETE_VARIANT_SUCCESS';
export const DELETE_VARIANT_FAIL = 'DELETE_VARIANT_FAIL';


export const CREATE_QUESTION_MULTI_REQUEST = 'CREATE_QUESTION_MULTI_REQUEST';
export const CREATE_QUESTION_MULTI_SUCCESS = 'CREATE_QUESTION_MULTI_SUCCESS';
export const CREATE_QUESTION_MULTI_FAIL = 'CREATE_QUESTION_MULTI_FAIL';
export const CREATE_QUESTION_MULTI_RESET = 'CREATE_QUESTION_MULTI_RESET';

export const GET_USERS_LIST_REQUEST = 'GET_USERS_LIST_REQUEST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_FAIL = 'GET_USERS_LIST_FAIL';
export const GET_USERS_LIST_RESET = 'GET_USERS_LIST_RESET';


export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const CREATE_USER_RESET = 'CREATE_USER_RESET';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const DELETE_USER_RESET = 'DELETE_USER_RESET';

export const UPDATE_ADMIN_REQUEST = 'UPDATE_ADMIN_REQUEST';
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS';
export const UPDATE_ADMIN_FAIL = 'UPDATE_ADMIN_FAIL';
export const UPDATE_ADMIN_RESET = 'UPDATE_ADMIN_RESET';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const GET_PROFILE_RESET = 'GET_PROFILE_RESET';

export const CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL';
export const CREATE_PROFILE_RESET = 'CREATE_PROFILE_RESET';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';

export const GET_LIST_PROFILES_REQUEST = 'GET_LIST_PROFILES_REQUEST';
export const GET_LIST_PROFILES_SUCCESS = 'GET_LIST_PROFILES_SUCCESS';
export const GET_LIST_PROFILES_FAIL = 'GET_LIST_PROFILES_FAIL';
export const GET_LIST_PROFILES_RESET = 'GET_LIST_PROFILES_RESET';

export const UPDATE_STORE_POS_REQUEST = 'UPDATE_STORE_POS_REQUEST';
export const UPDATE_STORE_POS_SUCCESS = 'UPDATE_STORE_POS_SUCCESS';
export const UPDATE_STORE_POS_FAIL = 'UPDATE_STORE_POS_FAIL';
export const UPDATE_STORE_POS_RESET = 'UPDATE_STORE_POS_RESET';