export const TEST_LIST_REQUEST = 'TEST_LIST_REQUEST';
export const TEST_LIST_SUCCESS = 'TEST_LIST_SUCCESS';
export const TEST_LIST_FAIL = 'TEST_LIST_FAIL';

export const TEST_TAKER_REQUEST = 'TEST_TAKER_REQUEST';
export const TEST_TAKER_SUCCESS = 'TEST_TAKER_SUCCESS';
export const TEST_TAKER_FAIL = 'TEST_TAKER_FAIL';

export const POST_RESULT_REQUEST = 'POST_RESULT_REQUEST';
export const POST_RESULT_SUCCESS = 'POST_RESULT_SUCCESS';
export const POST_RESULT_FAIL = 'POST_RESULT_FAIL';

export const GET_RESULTS_REQUEST = 'GET_RESULTS_REQUEST';
export const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS';
export const GET_RESULTS_FAIL = 'GET_RESULTS_FAIL';
export const GET_RESULTS_RESET = 'GET_RESULTS_RESET';

export const GET_RESULT_DETAILS_REQUEST = 'GET_RESULT_DETAILS_REQUEST';
export const GET_RESULT_DETAILS_SUCCESS = 'GET_RESULT_DETAILS_SUCCESS';
export const GET_RESULT_DETAILS_FAIL = 'GET_RESULT_DETAILS_FAIL';
