# Generated by Django 4.2.1 on 2023-05-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("test", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                ("variant", models.CharField(max_length=255)),
                ("is_right", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestQuery",
            fields=[
                ("total_questions", models.IntegerField()),
                ("answered_questions", models.IntegerField()),
                ("right_answered", models.IntegerField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "test_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionQuery",
            fields=[
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("answered", models.BooleanField()),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.question",
                    ),
                ),
                (
                    "test_query_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.testquery"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="test_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.test"
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("is_right", models.BooleanField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "question_query_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.questionquery",
                    ),
                ),
                (
                    "variant_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.variant",
                    ),
                ),
            ],
        ),
    ]
