# Generated by Django 4.2.1 on 2023-05-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_result_remove_questionquery_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("question_id", models.IntegerField()),
                ("variant_id", models.IntegerField()),
                ("is_right", models.BooleanField()),
                ("is_right_question", models.BooleanField()),
                ("is_checked", models.BooleanField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "result_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.result",
                    ),
                ),
            ],
        ),
    ]
