# Generated by Django 4.2.1 on 2023-05-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="test",
            name="entry_percent",
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="entry_questions",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.position",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.position",
            ),
        ),
    ]
