# Generated by Django 4.2.1 on 2023-05-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_question_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant", name="variant", field=models.TextField(),
        ),
    ]
